INSERT INTO "public"."operations" ("id", "created_at", "updated_at", "entered_at", "exited_at", "vehicle_type", "vehicle_model", "vehicle_plate", "operation_type") VALUES (1, now(), now(), now() - interval '7 day', null, 2, SUBSTR(UPPER(md5(random()::text)), 0 ,6), SUBSTR(UPPER(md5(random()::text)), 0 ,6), 0);
INSERT INTO "public"."operations" ("id", "created_at", "updated_at", "entered_at", "exited_at", "vehicle_type", "vehicle_model", "vehicle_plate", "operation_type") VALUES (2, now(), now(), now() - interval '6 day', null, 3, SUBSTR(UPPER(md5(random()::text)), 0 ,6), SUBSTR(UPPER(md5(random()::text)), 0 ,6), 0);
INSERT INTO "public"."operations" ("id", "created_at", "updated_at", "entered_at", "exited_at", "vehicle_type", "vehicle_model", "vehicle_plate", "operation_type") VALUES (3, now(), now(), now() - interval '5 day', null, 2, SUBSTR(UPPER(md5(random()::text)), 0 ,6), SUBSTR(UPPER(md5(random()::text)), 0 ,6), 0);
INSERT INTO "public"."operations" ("id", "created_at", "updated_at", "entered_at", "exited_at", "vehicle_type", "vehicle_model", "vehicle_plate", "operation_type") VALUES (4, now(), now(), now() - interval '4 day', null, 0, SUBSTR(UPPER(md5(random()::text)), 0 ,6), SUBSTR(UPPER(md5(random()::text)), 0 ,6), 0);
INSERT INTO "public"."operations" ("id", "created_at", "updated_at", "entered_at", "exited_at", "vehicle_type", "vehicle_model", "vehicle_plate", "operation_type") VALUES (5, now(), now(), now() - interval '3 day', null, 1, SUBSTR(UPPER(md5(random()::text)), 0 ,6), SUBSTR(UPPER(md5(random()::text)), 0 ,6), 0);
INSERT INTO "public"."operations" ("id", "created_at", "updated_at", "entered_at", "exited_at", "vehicle_type", "vehicle_model", "vehicle_plate", "operation_type") VALUES (6, now(), now(), now() - interval '2 day', null, 2, SUBSTR(UPPER(md5(random()::text)), 0 ,6), SUBSTR(UPPER(md5(random()::text)), 0 ,6), 0);
INSERT INTO "public"."operations" ("id", "created_at", "updated_at", "entered_at", "exited_at", "vehicle_type", "vehicle_model", "vehicle_plate", "operation_type") VALUES (7, now(), now(), now() - interval '1 day', null, 3, SUBSTR(UPPER(md5(random()::text)), 0 ,6), SUBSTR(UPPER(md5(random()::text)), 0 ,6), 0);
INSERT INTO "public"."operations" ("id", "created_at", "updated_at", "entered_at", "exited_at", "vehicle_type", "vehicle_model", "vehicle_plate", "operation_type") VALUES (8, now(), now(), now() - interval '0 day', null, 3, SUBSTR(UPPER(md5(random()::text)), 0 ,6), SUBSTR(UPPER(md5(random()::text)), 0 ,6), 0);

INSERT INTO "public"."operations" ("id", "created_at", "updated_at", "entered_at", "exited_at", "vehicle_type", "vehicle_model", "vehicle_plate", "operation_type") VALUES (9, now(), now(), now() - interval '8 day', null, 2, SUBSTR(UPPER(md5(random()::text)), 0 ,6), SUBSTR(UPPER(md5(random()::text)), 0 ,6), 0);
INSERT INTO "public"."operations" ("id", "created_at", "updated_at", "entered_at", "exited_at", "vehicle_type", "vehicle_model", "vehicle_plate", "operation_type") VALUES (10, now(), now(), now() - interval '9 day', null, 3, SUBSTR(UPPER(md5(random()::text)), 0 ,6), SUBSTR(UPPER(md5(random()::text)), 0 ,6), 0);
INSERT INTO "public"."operations" ("id", "created_at", "updated_at", "entered_at", "exited_at", "vehicle_type", "vehicle_model", "vehicle_plate", "operation_type") VALUES (11, now(), now(), now() - interval '10 day', null, 2, SUBSTR(UPPER(md5(random()::text)), 0 ,6), SUBSTR(UPPER(md5(random()::text)), 0 ,6), 0);
INSERT INTO "public"."operations" ("id", "created_at", "updated_at", "entered_at", "exited_at", "vehicle_type", "vehicle_model", "vehicle_plate", "operation_type") VALUES (12, now(), now(), now() - interval '11 day', null, 0, SUBSTR(UPPER(md5(random()::text)), 0 ,6), SUBSTR(UPPER(md5(random()::text)), 0 ,6), 0);
INSERT INTO "public"."operations" ("id", "created_at", "updated_at", "entered_at", "exited_at", "vehicle_type", "vehicle_model", "vehicle_plate", "operation_type") VALUES (13, now(), now(), now() - interval '12 day', null, 1, SUBSTR(UPPER(md5(random()::text)), 0 ,6), SUBSTR(UPPER(md5(random()::text)), 0 ,6), 0);
INSERT INTO "public"."operations" ("id", "created_at", "updated_at", "entered_at", "exited_at", "vehicle_type", "vehicle_model", "vehicle_plate", "operation_type") VALUES (14, now(), now(), now() - interval '13 day', null, 2, SUBSTR(UPPER(md5(random()::text)), 0 ,6), SUBSTR(UPPER(md5(random()::text)), 0 ,6), 0);
INSERT INTO "public"."operations" ("id", "created_at", "updated_at", "entered_at", "exited_at", "vehicle_type", "vehicle_model", "vehicle_plate", "operation_type") VALUES (15, now(), now(), now() - interval '14 day', null, 3, SUBSTR(UPPER(md5(random()::text)), 0 ,6), SUBSTR(UPPER(md5(random()::text)), 0 ,6), 0);
INSERT INTO "public"."operations" ("id", "created_at", "updated_at", "entered_at", "exited_at", "vehicle_type", "vehicle_model", "vehicle_plate", "operation_type") VALUES (16, now(), now(), now() - interval '15 day', null, 3, SUBSTR(UPPER(md5(random()::text)), 0 ,6), SUBSTR(UPPER(md5(random()::text)), 0 ,6), 0);

alter sequence hibernate_sequence RESTART 17;